# Generated by Django 5.2.10 on 2026-01-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='QUESTIONNAIRE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='donors.donor')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_serial_number', models.CharField(max_length=50, unique=True)),
                ('volume_ml', models.IntegerField(default=450)),
                ('successful', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phlebotomist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_draw', to='clinical.donorworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='clinical.donorworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('pulse', models.IntegerField()),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=4)),
                ('hemoglobin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='clinical.donorworkflow')),
            ],
        ),
    ]
