# Generated by Django 5.2.10 on 2026-01-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=500)),
                ('text_ar', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('General', 'General Health'), ('Travel', 'Travel History'), ('Medical', 'Medical Procedures'), ('HighRisk', 'High Risk Behaviors')], default='General', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('defer_if_answer_is', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', help_text='If user answers this, they are deferred.', max_length=3)),
                ('deferral_days', models.IntegerField(default=0, help_text='0 = Permanent Deferral, >0 = Temporary')),
            ],
        ),
    ]
