# Generated by Django 5.2.10 on 2026-01-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viral_status', models.CharField(choices=[('Pending', 'Pending'), ('Negative', 'Negative'), ('Positive', 'Positive')], default='Pending', max_length=20)),
                ('blood_group_result', models.CharField(blank=True, max_length=5, null=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test', to='clinical.donorworkflow')),
            ],
        ),
    ]
