# Generated by Django 5.2.10 on 2026-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='REGISTRATION', max_length=20),
        ),
    ]
