# Generated by Django 6.0.1 on 2026-01-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alter_donorworkflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_volume_ml', models.IntegerField(default=450)),
                ('min_volume_ml', models.IntegerField(default=400)),
                ('max_volume_ml', models.IntegerField(default=500)),
                ('min_duration_minutes', models.IntegerField(default=5, help_text='Minimum donation time before alerting flow issues.')),
                ('max_duration_minutes', models.IntegerField(default=15, help_text='Maximum duration before considering partial.')),
            ],
            options={
                'verbose_name_plural': 'Blood Collection Settings',
            },
        ),
        migrations.CreateModel(
            name='DeferralReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code e.g. 'LOW_HB'", max_length=20, unique=True)),
                ('reason_en', models.CharField(max_length=200)),
                ('reason_ar', models.CharField(max_length=200)),
                ('is_permanent', models.BooleanField(default=False)),
                ('default_duration_days', models.IntegerField(default=0, help_text='Default deferral duration in days.')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('deferral_days', models.IntegerField(default=0, help_text='Days to defer donor after taking this medication. 0 = Permanent.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('min_hemoglobin', models.DecimalField(decimal_places=1, default=12.5, max_digits=4)),
                ('max_temperature_c', models.DecimalField(decimal_places=1, default=37.5, max_digits=4)),
                ('max_systolic', models.IntegerField(default=180)),
                ('min_systolic', models.IntegerField(default=90)),
                ('max_diastolic', models.IntegerField(default=100)),
                ('min_diastolic', models.IntegerField(default=50)),
                ('max_pulse', models.IntegerField(default=100)),
                ('min_pulse', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'Vital Settings',
            },
        ),
    ]
