# Generated by Django 5.2.10 on 2026-01-31 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_collectionconfig_deferralreason_medication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(help_text="Unique key for code lookup e.g. 'bp_systolic'", unique=True)),
                ('category', models.CharField(choices=[('DEMOGRAPHICS', 'Demographics'), ('VITALS', 'Vital Signs'), ('LABS', 'Laboratory'), ('OTHER', 'Other')], default='VITALS', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ANY', 'Any')], default='ANY', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('deferral_days', models.IntegerField(default=0, help_text='Days to defer if rule is violated. 0 = Permanent/Manual Review')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
