# Generated by Django 5.2.10 on 2026-01-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_eligibilityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilityrule',
            name='deferral_code',
            field=models.CharField(blank=True, help_text="Code for auto-generated Deferral Reason e.g. 'VITAL_FAIL'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eligibilityrule',
            name='is_permanent_deferral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='deferral_days',
            field=models.IntegerField(default=0, help_text='Days to defer. Ignored if permanent.'),
        ),
    ]
