# Generated by Django 5.2.10 on 2026-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_eligibilityrule_deferral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionconfig',
            name='allow_manual_time_entry',
            field=models.BooleanField(default=False, verbose_name='Allow Manual Time Entry'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='enable_initial_label_stage',
            field=models.BooleanField(default=True, verbose_name='Enable Initial Label'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='enable_notifications_stage',
            field=models.BooleanField(default=True, verbose_name='Enable Notifications'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='enable_pre_donation_checks',
            field=models.BooleanField(default=True, verbose_name='Enable Pre-Donation Checks'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='enable_separation_stage',
            field=models.BooleanField(default=True, verbose_name='Enable Separation Stage'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='enable_untested_storage_stage',
            field=models.BooleanField(default=True, verbose_name='Enable Un-Tested Storage'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='require_arm_inspection',
            field=models.BooleanField(default=True, verbose_name='Require Both Arms Inspection'),
        ),
        migrations.AddField(
            model_name='collectionconfig',
            name='require_bag_inspection',
            field=models.BooleanField(default=True, verbose_name='Require Bag Visual Inspection'),
        ),
    ]
