# Generated by Django 6.0.1 on 2026-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_collectionconfig_allow_manual_time_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeparationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name e.g. 'Standard Leukoreduced RBC'", max_length=100)),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('RBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('LP', 'Liquid Plasma'), ('PLT', 'Platelets (Random)'), ('PLT_APH', 'Platelets (Apheresis)'), ('CRYO', 'Cryoprecipitate'), ('GRAN', 'Granulocytes')], default='RBC', max_length=10)),
                ('min_volume_ml', models.IntegerField(default=400, help_text='Min source volume required')),
                ('max_volume_ml', models.IntegerField(default=550, help_text='Max source volume allowed')),
                ('centrifuge_program', models.CharField(blank=True, help_text="e.g. 'Hard Spin 5000rpm 5min'", max_length=100)),
                ('expiration_hours', models.IntegerField(default=1008, help_text='Shelf life in hours from collection.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
