# Generated by Django 5.2.10 on 2026-01-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_productseparationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deferralreason',
            name='deferral_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('MEDICATION', 'Medication'), ('DISEASE', 'Disease'), ('TRAVEL', 'Travel')], default='REGULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='deferralreason',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description (AR)'),
        ),
        migrations.AddField(
            model_name='deferralreason',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='deferralreason',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deferralreason',
            name='default_duration_days',
            field=models.IntegerField(default=0, help_text='Blocking Days'),
        ),
        migrations.AlterField(
            model_name='deferralreason',
            name='reason_ar',
            field=models.CharField(max_length=200, verbose_name='Title (AR)'),
        ),
        migrations.AlterField(
            model_name='deferralreason',
            name='reason_en',
            field=models.CharField(max_length=200, verbose_name='Title (EN)'),
        ),
    ]
