# Generated by Django 5.2.10 on 2026-01-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_modificationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificationrequest',
            name='request_type',
            field=models.CharField(choices=[('COMPONENT', 'Component'), ('DONATION', 'Donation'), ('SETTINGS', 'Settings')], default='COMPONENT', max_length=20),
        ),
    ]
