# Generated by Django 6.0.1 on 2026-02-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_alter_modificationrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='iqama_checked',
            field=models.BooleanField(default=False),
        ),
    ]
