# Generated by Django 5.2.10 on 2026-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0013_vitalsigns_iqama_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('deferral_days', models.IntegerField(default=0, help_text='Days to defer donor after taking this medication. 0 = Permanent.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='blooddraw',
            old_name='phlebotomist',
            new_name='examiner',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='bag_serial_number',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='successful',
        ),
        migrations.RemoveField(
            model_name='blooddraw',
            name='volume_ml',
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='arm',
            field=models.CharField(blank=True, choices=[('Right', 'Right'), ('Left', 'Left')], max_length=10),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='bag_visual_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='blood_nature',
            field=models.CharField(default='Whole Blood', max_length=50),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='both_arm_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='drawn_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='drawn_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='first_unit_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='iqama_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='segment_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
