# Generated by Django 6.0.1 on 2026-02-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0014_componentdefinition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddraw',
            name='duration',
        ),
    ]
