# Generated by Django 6.0.1 on 2026-02-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0015_remove_blooddraw_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorworkflow',
            name='donation_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
