# Generated by Django 5.2.10 on 2026-02-05 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0016_donorworkflow_donation_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='REGISTRATION', max_length=20),
        ),
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_faint', models.BooleanField(default=False, verbose_name='Faint / Dizziness')),
                ('is_hematoma', models.BooleanField(default=False, verbose_name='Hematoma / Bruise')),
                ('is_nerve_injury', models.BooleanField(default=False, verbose_name='Nerve Injury')),
                ('is_arterial_puncture', models.BooleanField(default=False, verbose_name='Arterial Puncture')),
                ('is_citrate_reaction', models.BooleanField(default=False, verbose_name='Citrate Reaction')),
                ('is_other', models.BooleanField(default=False, verbose_name='Other')),
                ('other_description', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MILD', max_length=20)),
                ('onset_time', models.TimeField(blank=True, null=True)),
                ('ended_time', models.TimeField(blank=True, null=True)),
                ('management_notes', models.TextField(blank=True, help_text='What was done? (Ice pack, fluids, leg raise)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reaction', to='clinical.donorworkflow')),
            ],
        ),
    ]
