# Generated by Django 6.0.1 on 2026-02-05 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0017_alter_donorworkflow_status_adversereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('SURVEY', 'Post-Donation Survey'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='REGISTRATION', max_length=20),
        ),
        migrations.CreateModel(
            name='PostDonationSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_during_process', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], default=5, verbose_name='Comfort during donation')),
                ('staff_satisfaction', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], default=5, verbose_name='Satisfaction with Team')),
                ('wait_time_satisfaction', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral'), (4, 'Satisfied'), (5, 'Very Satisfied')], default=5, verbose_name='Satisfaction with Wait Time')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='clinical.donorworkflow')),
            ],
        ),
    ]
