# Generated by Django 5.2.11 on 2026-02-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0019_preseparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='preseparation',
            name='bag_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bag Expiry Date'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='bag_lot_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bag Lot No'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='bag_type',
            field=models.CharField(choices=[('Double_Filter', 'Double Filter'), ('Triple_Filter', 'Triple Filter'), ('Quadruple_Filter', 'Quadruple Filter'), ('Single', 'Single')], default='Double_Filter', max_length=50, verbose_name='Bag Type'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='donor_sample_label_check',
            field=models.BooleanField(default=False, verbose_name='Donor Sample Label Checked?'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='unit_label_check',
            field=models.BooleanField(default=False, verbose_name='Unit Label Check?'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='unit_temp_check',
            field=models.BooleanField(default=False, verbose_name='Unit Temp Checked?'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='visual_inspection',
            field=models.BooleanField(default=False, verbose_name='Visual Inspection?'),
        ),
        migrations.AddField(
            model_name='preseparation',
            name='volume_ml',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
