# Generated by Django 6.0.3 on 2026-04-11 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0022_laborder_labresult_delete_labtest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donorworkflow',
            name='workflow_type',
            field=models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood Donation'), ('APHERESIS', 'Apheresis Donation')], default='WHOLE_BLOOD', max_length=20, verbose_name='Donation Type'),
        ),
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('POST_DONATION', 'Post-Donation Care'), ('MEDICATION', 'Medication Review'), ('SURVEY', 'Post-Donation Survey'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], default='REGISTRATION', max_length=20),
        ),
        migrations.CreateModel(
            name='DonorMedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on_medication', models.BooleanField(default=False, verbose_name='Is Donor on Any Medication?')),
                ('other_medication_notes', models.TextField(blank=True, null=True, verbose_name='Other / Free-text Medications')),
                ('pharmacist_reviewed', models.BooleanField(default=False, verbose_name='Reviewed by Pharmacist?')),
                ('deferred_due_to_medication', models.BooleanField(default=False, verbose_name='Deferred Due to Medication?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medications_taken', models.ManyToManyField(blank=True, to='clinical.medication', verbose_name='Medications Listed')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medication_record', to='clinical.donorworkflow')),
            ],
        ),
        migrations.CreateModel(
            name='PostDonationCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felt_dizzy', models.BooleanField(default=False, verbose_name='Felt Dizzy?')),
                ('felt_nauseous', models.BooleanField(default=False, verbose_name='Felt Nauseous?')),
                ('felt_faint', models.BooleanField(default=False, verbose_name='Fainted?')),
                ('felt_well', models.BooleanField(default=True, verbose_name='Felt Well?')),
                ('given_refreshments', models.BooleanField(default=False, verbose_name='Refreshments Given?')),
                ('given_rest', models.BooleanField(default=False, verbose_name='Rest Given?')),
                ('applied_bandage', models.BooleanField(default=True, verbose_name='Bandage Applied?')),
                ('post_bp_systolic', models.IntegerField(blank=True, null=True, verbose_name='Post BP Systolic')),
                ('post_bp_diastolic', models.IntegerField(blank=True, null=True, verbose_name='Post BP Diastolic')),
                ('post_pulse', models.IntegerField(blank=True, null=True, verbose_name='Post Pulse')),
                ('rest_duration_minutes', models.IntegerField(default=15, verbose_name='Rest Duration (min)')),
                ('discharge_time', models.TimeField(blank=True, null=True, verbose_name='Discharge Time')),
                ('donor_instructions_given', models.BooleanField(default=True, verbose_name='Instructions Given?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_donation_care', to='clinical.donorworkflow')),
            ],
        ),
    ]
