# Generated by Django 6.0.3 on 2026-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0023_donorworkflow_workflow_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='General Health', help_text='Type Category Name (e.g. General, Travel)', max_length=100),
        ),
    ]
