# Generated by Django 6.0.3 on 2026-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0024_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='signature_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
