# Generated by Django 6.0.3 on 2026-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0025_questionnaireresponse_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(default='General', help_text='Grouping for the donor portal.', max_length=100),
        ),
    ]
