# Generated by Django 6.0.3 on 2026-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0026_medication_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('POST_DONATION', 'Post-Donation Care'), ('MEDICATION', 'Medication Review'), ('SURVEY', 'Post-Donation Survey'), ('LABS', 'Laboratory Testing'), ('PRE_DONATION_LAB', 'Pre-Donation Lab Check'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], db_index=True, default='REGISTRATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorworkflow',
            name='workflow_type',
            field=models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood Donation'), ('APHERESIS', 'Apheresis Donation')], db_index=True, default='WHOLE_BLOOD', max_length=20, verbose_name='Donation Type'),
        ),
    ]
