# Generated by Django 6.0.3 on 2026-04-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0027_alter_donorworkflow_created_at_and_more'),
        ('donors', '0006_alter_donor_email_alter_donor_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorworkflow',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow', to='donors.donorappointment'),
        ),
    ]
