# Generated by Django 6.0.3 on 2026-04-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0028_donorworkflow_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddraw',
            name='acd_lot_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='acd_lot_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='actual_acd_to_donor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='blood_volume_processed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='inventory_units_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='is_filtered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='kit_lot_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='kit_lot_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='machine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='platelets_collected_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='post_hct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='post_platelet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='procedure_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='total_acd_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='total_saline_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='volume_of_acd_in_platelets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='yield_of_platelets',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('MEDICATION', 'Medication Review'), ('VITALS', 'Vital Signs'), ('PRE_DONATION_LAB', 'Pre-Donation Lab Check'), ('COLLECTION', 'Blood Collection'), ('POST_DONATION', 'Post-Donation Care'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('PRE_SEPARATION', 'Pre-Separation Checks'), ('COMPONENTS', 'Component Extraction'), ('ATTACHMENT', 'Documentation/Attachments'), ('LABEL', 'Labeling'), ('SURVEY', 'Post-Donation Survey'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], db_index=True, default='REGISTRATION', max_length=20),
        ),
    ]
