# Generated by Django 6.0.3 on 2026-04-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0029_blooddraw_acd_lot_expiry_blooddraw_acd_lot_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddraw',
            name='pre_platelet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
