# Generated by Django 6.0.3 on 2026-04-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0030_blooddraw_pre_platelet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddraw',
            name='donation_reaction',
            field=models.BooleanField(default=False),
        ),
    ]
