# Generated by Django 6.0.3 on 2026-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0032_donorworkflow_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('MEDICATION', 'Medication Review'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('POST_DONATION', 'Post-Donation Care'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('PRE_SEPARATION', 'Pre-Separation Checks'), ('COMPONENTS', 'Component Extraction'), ('ATTACHMENT', 'Documentation/Attachments'), ('LABEL', 'Labeling'), ('SURVEY', 'Post-Donation Survey'), ('LABS', 'Laboratory Testing'), ('COMPLETED', 'Completed'), ('DEFERRED', 'Deferred')], db_index=True, default='REGISTRATION', max_length=20),
        ),
    ]
