# Generated by Django 6.0.3 on 2026-04-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0033_alter_donorworkflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddraw',
            name='apheresis_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddraw',
            name='apheresis_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
