# Generated by Django 6.0.3 on 2026-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0034_add_apheresis_time_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorworkflow',
            name='status',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('QUESTIONNAIRE', 'Medical Questionnaire'), ('MEDICATION', 'Medication Review'), ('VITALS', 'Vital Signs'), ('COLLECTION', 'Blood Collection'), ('POST_DONATION', 'Post-Donation Care'), ('ADVERSE_REACTION', 'Adverse Reaction'), ('SURVEY', 'Post-Donation Survey'), ('DEFERRED', 'Deferred'), ('PRE_SEPARATION', 'Pre-Separation Checks'), ('COMPONENTS', 'Component Extraction'), ('ATTACHMENT', 'Attachments'), ('LABEL', 'Labeling'), ('LABS', 'Laboratory Testing'), ('SELF_EXCLUSION', 'Self Exclusion'), ('STATUS_HISTORY', 'Status History'), ('COMPLETED', 'History')], db_index=True, default='REGISTRATION', max_length=20),
        ),
    ]
