# Generated by Django 6.0.1 on 2026-02-08 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0018_alter_donorworkflow_status_postdonationsurvey'),
        ('donors', '0002_nationality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDeferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Title / Reason')),
                ('deferral_type', models.CharField(choices=[('TEMPORARY', 'Temporary'), ('PERMANENT', 'Permanent')], default='TEMPORARY', max_length=20)),
                ('donor_value', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('days_blocked', models.IntegerField(default=0, help_text='Number of days blocked')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='donors.donor')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferrals_created', to='clinical.donorworkflow')),
            ],
        ),
    ]
