# Generated by Django 6.0.3 on 2026-04-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_email_donor_user_donorappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Hospital Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hospital / Collection Center',
                'verbose_name_plural': 'Hospitals / Collection Centers',
            },
        ),
        migrations.AlterField(
            model_name='donorappointment',
            name='hospital_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hospital Branch'),
        ),
        migrations.AddField(
            model_name='donorappointment',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='donors.hospital'),
        ),
    ]
