# Generated by Django 6.0.3 on 2026-04-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_hospital_alter_donorappointment_hospital_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='donorappointment',
            name='appointment_date',
            field=models.DateField(db_index=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='donorappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
