# Generated by Django 6.0.3 on 2026-04-20 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_donor_email_alter_donor_mobile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['national_id'], name='donors_dono_nationa_90af50_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['full_name'], name='donors_dono_full_na_9f3576_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['mobile'], name='donors_dono_mobile_aef755_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['created_at'], name='donors_dono_created_d12ba8_idx'),
        ),
    ]
