# Generated by Django 6.0.3 on 2026-04-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_ai',
            field=models.BooleanField(default=False, verbose_name='AI Manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_clinical',
            field=models.BooleanField(default=False, verbose_name='Clinical & Lab'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_donations',
            field=models.BooleanField(default=False, verbose_name='Donation Workflow'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_donors',
            field=models.BooleanField(default=False, verbose_name='Donors Management'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_inventory',
            field=models.BooleanField(default=False, verbose_name='Inventory & Store'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_orders',
            field=models.BooleanField(default=False, verbose_name='Orders & Requests'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_reports',
            field=models.BooleanField(default=False, verbose_name='Reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_access_settings',
            field=models.BooleanField(default=False, verbose_name='System Settings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='', help_text='e.g. Doctor, Nurse, Lab Technician, Receptionist', max_length=100, verbose_name='Role / Job Title'),
        ),
    ]
