# Generated by Django 6.0.3 on 2026-04-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_can_access_ai_user_can_access_clinical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access_dashboard',
            field=models.BooleanField(default=True, verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_clinical',
            field=models.BooleanField(default=False, verbose_name='Lab Result'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_donations',
            field=models.BooleanField(default=False, verbose_name='Donation Process'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_donors',
            field=models.BooleanField(default=False, verbose_name='Main Navigation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_inventory',
            field=models.BooleanField(default=False, verbose_name='Inventory & Labs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_orders',
            field=models.BooleanField(default=False, verbose_name='Blood Order Process / Patient Services'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_access_settings',
            field=models.BooleanField(default=False, verbose_name='Administration'),
        ),
    ]
