# Generated by Django 6.0.3 on 2026-04-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_can_access_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id_length', models.IntegerField(default=10, help_text='Required length for National ID')),
                ('donor_phone_length', models.IntegerField(default=10, help_text='Required length for Phone Number')),
                ('donor_phone_prefix', models.CharField(default='0', help_text='Required prefix for Phone Number', max_length=5)),
                ('donor_min_age', models.IntegerField(default=18, help_text='Minimum allowed age for donors')),
                ('donor_max_age', models.IntegerField(default=60, help_text='Maximum allowed age for donors')),
            ],
            options={
                'verbose_name': 'Global System Rules',
                'verbose_name_plural': 'Global System Rules',
            },
        ),
    ]
