# Generated by Django 6.0.3 on 2026-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_access_dashboard',
            field=models.BooleanField(default=False, verbose_name='Dashboard'),
        ),
    ]
