# Generated by Django 5.2.10 on 2026-01-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('PRBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('PLT', 'Platelets'), ('CRYO', 'Cryoprecipitate')], max_length=10)),
                ('unit_number', models.CharField(help_text='e.g. UNIT-12345-01', max_length=50, unique=True)),
                ('segment_number', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(db_index=True, max_length=5)),
                ('volume_ml', models.IntegerField()),
                ('status', models.CharField(choices=[('QUARANTINE', 'Quarantine (Untested)'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('TRANSFUSED', 'Transfused'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='QUARANTINE', max_length=20)),
                ('location', models.CharField(default='Processing Fridge', max_length=100)),
                ('manufactured_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='clinical.donorworkflow')),
            ],
        ),
    ]
