# Generated by Django 6.0.1 on 2026-01-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_separation', models.BooleanField(default=True, help_text='Automatically create components upon collection completion?')),
                ('default_components', models.JSONField(default=list, help_text="List of component types to create by default e.g. ['PRBC', 'FFP']")),
                ('expiration_days_prbc', models.IntegerField(default=35)),
                ('expiration_days_ffp', models.IntegerField(default=365)),
                ('expiration_days_plt', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': 'Separation Settings',
            },
        ),
    ]
