# Generated by Django 6.0.1 on 2026-02-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_separationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcomponent',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='room_temp_check',
            field=models.BooleanField(default=False, verbose_name='Room Temperature Check'),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='storage_time_after_prep',
            field=models.TimeField(blank=True, null=True, verbose_name='Storage Time After Preparation'),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='visual_inspection',
            field=models.BooleanField(default=False, verbose_name='Visual Inspection'),
        ),
    ]
