# Generated by Django 6.0.3 on 2026-04-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_bloodcomponent_notes_bloodcomponent_room_temp_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodcomponent',
            name='blood_group',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
