# Generated by Django 6.0.3 on 2026-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_blood_group_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodcomponent',
            name='volume_ml',
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='is_labeled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
