# Generated by Django 6.0.3 on 2026-04-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bloodcomponent_created_by_bloodcomponent_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcomponent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_components', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodcomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
