# Generated by Django 6.0.3 on 2026-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_updated_at_approved_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcomponent',
            name='bacterial_contamination',
            field=models.CharField(default='None', max_length=50, verbose_name='Bacterial Contamination'),
        ),
    ]
