# Generated by Django 5.2.10 on 2026-01-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn', models.CharField(help_text='Medical Record Number', max_length=50)),
                ('patient_full_name', models.CharField(max_length=200)),
                ('patient_blood_group', models.CharField(max_length=5)),
                ('hospital_ward', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('WB', 'Whole Blood'), ('PRBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('PLT', 'Platelets'), ('CRYO', 'Cryoprecipitate')], max_length=10)),
                ('units_requested', models.IntegerField(default=1)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Life Threatening (Emergency)')], default='ROUTINE', max_length=20)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Request'), ('CROSSMATCHING', 'Crossmatching'), ('ISSUED', 'Issued/Dispensed'), ('COMPLETED', 'Completed/Transfused'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crossmatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compatible', models.BooleanField(default=False)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches', to='orders.bloodorder')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches', to='inventory.bloodcomponent')),
            ],
            options={
                'unique_together': {('order', 'unit')},
            },
        ),
    ]
