# Generated by Django 6.0.3 on 2026-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodorder',
            name='component_type',
            field=models.CharField(choices=[('WB', 'Whole Blood'), ('PRBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('PLT', 'Platelets'), ('CRYO', 'Cryoprecipitate'), ('APHERESIS', 'Apheresis Component')], max_length=10),
        ),
    ]
